spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file_management?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 9090  # Port pour stage
  servlet:
    context-path: /api