spring.application.name=file-managment

spring.servlet.multipart.max-file-size = 20MB
spring.servlet.multipart.max-request-size = 20MB
spring.servlet.multipart.enabled = true
server.servlet.context-path=/api

file.upload-dir = ./uploads

server.port = 9090

spring.jpa.hibernate.ddl-auto = update
spring.datasource.url = jdbc:mysql://localhost:3306/file_managment
spring.datasource.username = root
spring.datasource.password = password
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.show-sql = true

# Force le chemin du JSON pour Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=alpha
# Autorise l'accès au JSON
springdoc.api-docs.enabled=true




