spring.application.name=file-managment

spring.servlet.multipart.max-file-size = 20MB
spring.servlet.multipart.max-request-size = 20MB
spring.servlet.multipart.enabled = true
server.servlet.context-path=/api

file.upload-dir = ./uploads

server.port = 6000

spring.jpa.hibernate.ddl-auto = update
spring.datasource.url = jdbc:mysql://localhost:3306/file_managment
spring.datasource.username = root
spring.datasource.password = password
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.show-sql = true

# Force l'activation de swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Si vous voulez accéder à swagger via http://localhost:5000/api-docs
springdoc.swagger-ui.path=/api-docs



